### ISSUE TITLE
Kate Recipe

### ISSUE THREAD

**Issue by jkshepperson** [RedesignChallenge/challenge-platform#25]
Within **Develop Recipe**, post the Kate-Recipe information to the following section:
_Want great feedback in a safe and supportive space?_

Kate-Recipe content:
[Kate-Recipe.txt](https://github.com/RedesignChallenge/challenge-platform/files/283020/Kate-Recipe.txt)

**Comment by MakotoTheKnight** [comment]
Is the title on this recipe correct?  I'll leave it in an unpublished state until I can get confirmation on that.

**Comment by jkshepperson** [comment]
Nope I forgot to change it - thank you and great catch! Here is her title: 

iSee: A Video-Feedback Process Focused on Teachers’ Own Goals
