### ISSUE TITLE
Port over the proprietary source code

### ISSUE THREAD

**Issue by jkshepperson** [RedesignChallenge/challenge-platform#3]
Migrate the proprietary RDC code to the new open source view. Keep in mind that the architecture will need support custom styles during future use.

**Comment by MakotoTheKnight** [comment]
This task will cover:

- [ ] Importing the latest code from upstream, preserving history
- [ ] Removing external dependencies on third party services (S3, Twitter, Mandrill, etc)
- [ ] Ensuring that the application will start
- [ ] Ensuring that the README is up to date
