### ISSUE TITLE
Create docker containers

### ISSUE THREAD

**Issue by jkshepperson** [RedesignChallenge/challenge-platform#4]

**Comment by MakotoTheKnight** [comment]
After attempting to experiment with this, I'm coming to the conclusion that this isn't a bridge we want to cross at this time.  Reasons:

 - The images for Ruby and Heroku are fairly large
 - You cannot rely on the Gemfile for the version of Ruby you want - at the time of writing the Heroku gem has hard-coded 2.2.3 as their Ruby version of choice
 - The size of these containers can get unwieldy fairly fast
 - It doesn't immediately solve any pain points; developers that wish to run this application would be more at home with running `rails s` than they would with downloading and configuring Docker

Right now, we're probably not going to want to do this.  But we should revisit this in the future.
