### ISSUE TITLE
Cannot bootstrap application with a completely empty database

### ISSUE THREAD

**Issue by MakotoTheKnight** [RedesignChallenge/challenge-platform#42]
When using an unseeded database to connect against, the home page refuses to load due to a hard assumption that we have either a featured challenge or challenges at all.

In an empty state, we should not require seed data to have been run.

**Comment by jkshepperson** [comment]
Potentially covered in the README, Joell will re-read this morning to see if changes should be made to make this instruction explicitly clear.

**Comment by jkshepperson** [comment]
I believe this task is complete. The instance mentioned in the original task regarding the requirement of seed data before running the application is mentioned in the following locations, in the first couple of sections no less:
- Application Flow documentation, 'Initializing data' section
- README documentation, 'Seeding and Recreating the Databases' section

Both are clear to understand and mention that it is a minimum requirement of the system to be run correctly. 

@Jason: if this is ok with you I think we're good to go!

**Comment by MakotoTheKnight** [comment]
It's good with me - I'll go ahead and close this task out then.
