### ISSUE TITLE
Create rough-flow documentation

### ISSUE THREAD

**Issue by jkshepperson** [RedesignChallenge/challenge-platform#45]
Understanding the basic touch points/interactions for:
- unregistered users 
- registered users
- admins

Emphasize details of differences between roles and steps to using the application.

**Comment by jkshepperson** [comment]
Awesome layout, very clear and easy to read. Few minor changes noted below:

- Within the 'Creating Solutions and Solution Stories' section, under subheader "Creating the Solution":
  - For step 3, a question: is 'here' in italics because it is supposed to be linked to something or is it just referencing the way it is written in the CMS?
  - For step 4, a small fix: remove the word 'in' from the instructional sentence...you seem to use the phrase 'fill out' more consistently throughout the document
![image1](https://cloud.githubusercontent.com/assets/15215098/16418276/1427dfda-3d17-11e6-9aa6-4061ca514edb.png)

  - For step 8, a clarification: I'm not sure how we want to handle this in the notes but I tested these sequence of steps and it doesn't seem to matter if you add the step as a 'steppable solution' or not. It seems to be attributed automatically upon saving the new step. For an example of this live check out any of the solutions I entered yesterday - for all of them I didn't add them as stepabble upon input but when you go back into the solution you can see that the drop down has now been selected automatically for me.  Just a note and point of clarification... when I tried to manually add the step-able selection to my stories I had to first go to a Steps section in the CMS to add them there and then try to pull them in which was much more difficult.

**Comment by MakotoTheKnight** [comment]
Thanks for the feedback @jkshepperson - I've made the corrections to the Wiki document.

As for Step 8, I'm fine with leaving that off if it's unnecessary - the likely scenario is that a user will be creating the steps at the same time they're creating the solution, so Steppable will be automatically bound to the solution, thus removing the need to place it here.

Let me know if there are any other points that need to be improved.

**Comment by jkshepperson** [comment]
This is all good! Thanks for updating!
