### ISSUE TITLE
Review localization of existing code

### ISSUE THREAD

**Issue by jkshepperson** [RedesignChallenge/challenge-platform#5]
Review existing localization and clean up easy-to-make fixes in the process. Log any additional tickets or work that will need to be considered to ensure clean delivery for later prioritization.

**Comment by MakotoTheKnight** [comment]
There is still some cleanup to do with the strings, but _most_ of them are here.  We'll want to tackle these pieces and ensure that we've got a good baseline for i18n:

 - Convert all pages in the project to use I18n (described in #31, #32, #33, #34, #35, #36, and #37)
 - Remove any and all HTML from these strings

What I've done in this task is ensure that the entire homepage was using these strings, and that there weren't any strings listed in the home section that weren't already in use.

I'll move on to #31 for the time being to keep things going with the localization effort.
