### ISSUE TITLE
Fix Rails Admin

### ISSUE THREAD

**Issue by jkshepperson** [RedesignChallenge/challenge-platform#6]
Ensure that the hot fixes done to support the system are reflected in the Rails Admin

**Comment by MakotoTheKnight** [comment]
I've managed to recover the original pain point about this aspect of it, and here's what I can surmise.

It seems that, when either an experience, step or recipe is created without there being one prior, Rails Admin would error out.  However, the error message has not been cleanly preserved.

On a smoke test, we had an issue with a Kaminari initializer which would mysteriously break if the collection provided to it was empty.  Upon analysis of this and the upstream project, there is no Kaminari initializer to be found, so it's been removed from this project and pieces seem to be working.

With the merge pending, I will tentatively close this issue.  If this crops up again, we should document what the actual trouble is when we are creating new pieces of content through Rails Admin.
